# Site settings
author: Sean Fyffe
title: My Coding Journey
header-img: img/home-bg.png
email: stfyffe@gmail.com
copyright_name: Sean Fyffe
description: > # this means to ignore newlines until "baseurl:"
  Learning to code for a brighter future
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sfyffe1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
